[env]
  TERM = "xterm-256color"

# Font (FiraCode)
[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

# Colors (Nord)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'
